apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: inje-msa-demo-dev
commonLabels:
  app: book-service
images:
- name: book-service
  newName: harbor.cone-chain.com/inje-msa-demo-dev/inje-msa-demo/book-service
  newTag: latest
patches:
- target:
    kind: Deployment
    name: book-service-dp
  patch: |-
    kind: Deployment
    metadata:
      name: book-service-dp
    spec:
      template:
        spec:
          # nodeSelector:
          #   magnum.openstack.org/nodegroup: shh
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - dev-shh-node-0
                    - dev-shh-node-1
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: book-service
                  topologyKey: kubernetes.io/hostname
                weight: 1
          containers:
          - name: book-service-con
            env:
            # - name: JAVA_OPTS
            #   value: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=dev"
            ###
            # OpenTelemetry Application Performance Management
            ## https://github.com/blueswen/opentelemetry-apm?tab=readme-ov-file#java---spring-boot
            - name: JAVA_OPTS
              value: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=dev -javaagent:/app/opentelemetry-javaagent.jar"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_SERVICE_NAME
              value: book-service
            resources:
              limits:
                cpu: 800m
                ephemeral-storage: 1Gi
                memory: 1500Mi
              requests:
                cpu: 400m
                ephemeral-storage: 300Mi
                memory: 1200Mi
            ###    
- target:
    kind: PersistentVolumeClaim
    name: book-service-data-pvc
  patch: |-
    kind: PersistentVolumeClaim
    metadata:
      name: book-service-data-pvc
    spec:
      resources:
        requests:
          storage: 1Gi
      storageClassName: app-sc    
- target:
    kind: PersistentVolumeClaim
    name: book-service-log-pvc
  patch: |-
    kind: PersistentVolumeClaim
    metadata:
      name: book-service-log-pvc
    spec:
      resources:
        requests:
          storage: 5Gi
      storageClassName: app-sc
