apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-client-log-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: app-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-client-dp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: book-client-con
        image: book-client
        imagePullPolicy: Always
        securityContext:
          # allowPrivilegeEscalation: false
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 101
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: NODE_NAME
          valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
        - name: NODE_IP
          valueFrom: {fieldRef: {fieldPath: status.hostIP}}
        - name: NAMESPACE
          valueFrom: {fieldRef: {fieldPath: metadata.namespace}}
        - name: POD_NAME
          valueFrom: {fieldRef: {fieldPath: metadata.name}}
        - name: POD_IP
          valueFrom: {fieldRef: {fieldPath: status.podIP}}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 400m
            ephemeral-storage: 1Gi
            memory: 1200Mi
          requests:
            cpu: 200m
            ephemeral-storage: 300Mi
            memory: 800Mi
        volumeMounts:
        - mountPath: /var/log/nginx
          name: log
        - mountPath: /var/cache/nginx
          name: cache
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: default-conf
          subPath: default.conf
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: book-client-log-pvc
      - emptyDir: {}
        name: cache
      - emptyDir: {}
        name: tmp
      - configMap:
          items:
          - key: nginx.conf
            path: nginx.conf
          name: book-client-nginx-cm
        name: nginx-conf
      - configMap:
          items:
          - key: default.conf
            path: default.conf
          name: book-client-nginx-cm
        name: default-conf
---
apiVersion: v1
kind: Service
metadata:
  name: book-client-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80