apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  labels:
    app: discovery-server
    env: dev
    type: deploy
  name: discovery-server-dev-deploy-el
  namespace: inje-msa-demo-cicd
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: cicdbot
  triggers:
  - name: trigger
    bindings:
    - kind: TriggerBinding
      name: git-host-url
      value: $(body.git-host-url)
    - kind: TriggerBinding
      name: code-repo-org
      value: $(body.code-repo-org)
    - kind: TriggerBinding
      name: code-repo-name
      value: $(body.code-repo-name)
    - kind: TriggerBinding
      name: cicd-revision
      value: $(body.cicd-revision)
    template:
      ref: discovery-server-dev-deploy-tt